# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomNumber', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('occupied', models.BooleanField(verbose_name='Занята')),
            ],
            options={
                'ordering': ('roomNumber',),
                'verbose_name_plural': 'Комнаты',
                'verbose_name': 'Комната',
            },
        ),
    ]
