# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webName', models.CharField(max_length=5, verbose_name='Индентификатор')),
                ('phoneNumber', models.CharField(max_length=18, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('address', models.CharField(max_length=30, verbose_name='Аддрес')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакты',
            },
        ),
    ]
