# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Аддрес'),
        ),
    ]
